#+TITLE: Pract1
* Base de Datos CINE
** Consultas sobre una sola tabla
*** 1. Obtener ordenados ascendentemente los códigos de los países de donde son los actores
#+begin_src sql
SELECT DISTINCT cod_pais
FROM actor
ORDER BY cod_pais;
#+end_src
*** 2. Obtener el código y el título de las películas de año anterior a 1970 que no estén basadas en ningún libro ordenadas por título.
#+begin_src sql
SELECT cod_peli, titulo
FROM pelicula
WHERE anyo < 1970 AND cod_lib IS NULL
ORDER BY titulo;
#+end_src
*** TODO 3. Obtener el código y el nombre de los actores cuyo nombre incluye “John”.
#+begin_src sql
SELECT cod_act, nombre
FROM actor
WHERE nombre LIKE '%John%'
#+end_src
*** 4. Obtener el código y el título de las películas de más de 120 minutos de la década de los 80
#+begin_src sql
SELECT cod_peli, titulo
FROM pelicula
WHERE duracion > 120 AND anyo BETWEEN 1980 AND 1989
ORDER BY titulo;
#+end_src
*** TODO 5. Obtener el código y el título de las películas que estén basadas en algún libro y cuyo director se apellide ‘Pakula’.
#+begin_src sql
SELECT cod_peli, titulo
FROM pelicula
WHERE cod_lib is not null and director LIKE '% Pakula%'
#+end_src
*** 6. ¿Cuántas películas hay de más de 120 minutos de la década de los 80?
#+begin_src sql
SELECT count(*)
FROM pelicula
WHERE duracion > 120 AND anyo BETWEEN 1980 AND 1989
ORDER BY titulo;
#+end_src
*** 7. ¿Cuántas películas se han clasificado de los géneros de código 'BB5' o 'GG4' o'JH6'?
#+begin_src sql
SELECT count(DISTINCT cod_peli)
FROM clasificacion
WHERE cod_gen IN('BB5','GG4','JH6')
#+end_src
*** 8. ¿De qué año es el libro más antiguo?
#+begin_src sql
SELECT MIN(anyo)
FROM libro_peli
#+end_src
*** 9. ¿Cuál es la duración media de las películas del año 1987?
#+begin_src sql
SELECT AVG(duracion)
FROM pelicula
WHERE anyo=1987
#+end_src
*** 10. ¿Cuántos minutos ocupan todas las películas dirigidas por ‘Steven Spielberg’?
#+begin_src sql
SELECT SUM(duracion)
FROM pelicula
WHERE director='Steven Spielberg'
#+end_src
** Consultas sobre varias tablas
*** 11. Obtener el código y el título de las películas en las que actúa un actor con el mismo nombre que el director
de la película (ordenadas por título).
#+begin_src sql
SELECT p.cod_peli, p.titulo
FROM pelicula p, actua act, actor atr
WHERE act.cod_act=atr.cod_act and act.cod_peli=p.cod_peli and p.director=atr.nombre
ORDER BY p.titulo
#+end_src
*** 12. Obtener el código y el título de las películas clasificadas del género de nombre ‘Comedia’ (ordenadas por
título).
#+begin_src sql
SELECT p.cod_peli, p.titulo
FROM pelicula p, clasificacion c, genero g
WHERE g.nombre='Comedia' and g.cod_gen=c.cod_gen and c.cod_peli=p.cod_peli
ORDER BY p.titulo
#+end_src
*** 13. Obtener el código y el título de las películas basadas en algún libro anterior a 1950
#+begin_src sql
SELECT cod_peli, pelicula.titulo
FROM pelicula, libro --Producto cartesiano de pelicula X libro
WHERE pelicula.cod_lib = libro.cod_lib AND libro.anyo < 1950
#+end_src
*** 14. Obtener el código y el nombre de los países de los actores que actúan en películas clasificadas del género de nombre ‘Comedia’ (ordenados por nombre).
#+begin_src sql
SELECT DISTINCT pa.cod_pais, pa.nombre
FROM pais pa, actor atr, actua act, pelicula pe, clasificacion c, genero g
WHERE g.nombre='Comedia' and g.cod_gen=c.cod_gen and c.cod_peli=pe.cod_peli and pe.cod_peli=act.cod_peli and act.cod_act=atr.cod_act and atr.cod_pais=pa.cod_pais
ORDER BY pa.nombre
#+end_src

/Otra manera/

#+begin_src sql
SELECT DISTINCT pa.cod_pais, pa.nombre
FROM pais pa, actor atr, actua act, pelicula pe, clasificacion c, genero g
WHERE g.nombre='Comedia' and g.cod_gen=c.cod_gen and c.cod_peli=act.cod_peli and act.cod_act=atr.cod_act and atr.cod_pais=pa.cod_pais
ORDER BY pa.nombre
#+end_src
